DELETE FROM course;
INSERT INTO course (course_id, title) VALUES ("AFST 100", "Introduction to The Black Experience");
INSERT INTO course (course_id, title) VALUES ("AFST 205", "Contemporary Black Popular Culture");
INSERT INTO course (course_id, title) VALUES ("AFST 206", "Introduction to African-American History: A Survey");
INSERT INTO course (course_id, title) VALUES ("AFST 211", "Introduction to Contemporary Africa");
INSERT INTO course (course_id, title) VALUES ("AFST 213", "Africa: Culture and Development");
INSERT INTO course (course_id, title) VALUES ("AFST 215", "Introduction to African Dance");
INSERT INTO course (course_id, title) VALUES ("AFST 245", "Introduction to Black Music");
INSERT INTO course (course_id, title) VALUES ("AFST 255", "Psychology of the Black Experience in the United States");
INSERT INTO course (course_id, title) VALUES ("AFST 261", "Black Literature: Twentieth Century");
INSERT INTO course (course_id, title) VALUES ("AFST 314", "Islam in Africa");
INSERT INTO course (course_id, title) VALUES ("AFST 347", "Gender, Race, and Media");
INSERT INTO course (course_id, title) VALUES ("AFST 353", "African American History Since 1865");
INSERT INTO course (course_id, title) VALUES ("AFST 360", "Studies in Black Fiction");
INSERT INTO course (course_id, title) VALUES ("AFST 369", "Black Families in the United States");
INSERT INTO course (course_id, title) VALUES ("AFST 439", "Women in Africa and the Diaspora");
INSERT INTO course (course_id, title) VALUES ("AFST 440", "Topics in African and African-American Studies");
INSERT INTO course (course_id, title) VALUES ("AFST 495", "Field Research in Africana Studies");
INSERT INTO course (course_id, title) VALUES ("AGNG 100", "So You Say You Want a Revolution: How Boomers are Revolutionizing Aging");
INSERT INTO course (course_id, title) VALUES ("AGNG 100Y", "So You Say You Want a Revolution: How Boomers are Revolutionizing Aging");
INSERT INTO course (course_id, title) VALUES ("AGNG 200", "Aging People, Policy and Management");
INSERT INTO course (course_id, title) VALUES ("AGNG 200Y", "Aging People, Policy and Management");
INSERT INTO course (course_id, title) VALUES ("AGNG 300", "Policy Analysis for Aging Issues");
INSERT INTO course (course_id, title) VALUES ("AGNG 310", "Overview of Management in Aging");
INSERT INTO course (course_id, title) VALUES ("AGNG 320", "Strength-Based Approaches to Promoting Health and Wellness in Aging");
INSERT INTO course (course_id, title) VALUES ("AGNG 351", "Business Decision Making for Aging Services");
INSERT INTO course (course_id, title) VALUES ("AGNG 415", "The Art of Aging");
INSERT INTO course (course_id, title) VALUES ("AGNG 460", "Management of Aging Services Internship");
INSERT INTO course (course_id, title) VALUES ("AGNG 462", "Internship - Aging Services II");
INSERT INTO course (course_id, title) VALUES ("AGNG 470", "Aging Service Management: Capstone Seminar");
INSERT INTO course (course_id, title) VALUES ("AMST 100", "Introduction to American Studies");
INSERT INTO course (course_id, title) VALUES ("AMST 100Y", "Introduction to American Studies");
INSERT INTO course (course_id, title) VALUES ("AMST 200", "What is an American?");
INSERT INTO course (course_id, title) VALUES ("AMST 210", "Introduction to Critical Sexuality Studies");
INSERT INTO course (course_id, title) VALUES ("AMST 300", "Approaches in American Studies");
INSERT INTO course (course_id, title) VALUES ("AMST 320", "Television in American Culture");
INSERT INTO course (course_id, title) VALUES ("AMST 322", "American Society and Culture in Film");
INSERT INTO course (course_id, title) VALUES ("AMST 352", "American Culture in Global Perspective");
INSERT INTO course (course_id, title) VALUES ("AMST 375", "Studies in Asian American Culture");
INSERT INTO course (course_id, title) VALUES ("AMST 376", "The American Dream");
INSERT INTO course (course_id, title) VALUES ("AMST 464", "Narratives of Contemporary U.S. Immigration");
INSERT INTO course (course_id, title) VALUES ("AMST 490", "Senior Seminar");
INSERT INTO course (course_id, title) VALUES ("ANCS 150", "English Word Roots from Latin and Greek");
INSERT INTO course (course_id, title) VALUES ("ANCS 202", "The Roman World");
INSERT INTO course (course_id, title) VALUES ("ANCS 220", "Judaism in the Time of Jesus and Hillel");
INSERT INTO course (course_id, title) VALUES ("ANCS 375", "Ancient Medicine");
INSERT INTO course (course_id, title) VALUES ("ANTH 101", "Introduction to Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 211", "Cultural Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 211Y", "Cultural Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 214", "Focused Cultural Study: South Asia");
INSERT INTO course (course_id, title) VALUES ("ANTH 302", "Human Evolution, Physical Anthropology and Archaeology");
INSERT INTO course (course_id, title) VALUES ("ANTH 310", "Ethnographic Film");
INSERT INTO course (course_id, title) VALUES ("ANTH 313", "Applied Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 397", "Selected Topics in Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 424", "Psychological Anthropology");
INSERT INTO course (course_id, title) VALUES ("ANTH 480", "Anthropological Research: Capstone");
INSERT INTO course (course_id, title) VALUES ("ARBC 102", "Elementary Arabic II");
INSERT INTO course (course_id, title) VALUES ("ARBC 202", "Intermediate Arabic II");
INSERT INTO course (course_id, title) VALUES ("ARBC 302", "Advanced Modern Standard Arabic II");
INSERT INTO course (course_id, title) VALUES ("ARCH 201", "Roman Archaeology and Art");
INSERT INTO course (course_id, title) VALUES ("ARCH 330", "Archaeology of the Prehistoric Aegean");
INSERT INTO course (course_id, title) VALUES ("ARCH 340", "Cities of the Past");
INSERT INTO course (course_id, title) VALUES ("ARCH 350", "Topics in Archaeology");
INSERT INTO course (course_id, title) VALUES ("ART 210", "Visual Concepts I");
INSERT INTO course (course_id, title) VALUES ("ART 211", "Visual Concepts II/Camera Vision");
INSERT INTO course (course_id, title) VALUES ("ART 212", "Visual Concepts III/Three Dimensional Form, Space and Interaction");
INSERT INTO course (course_id, title) VALUES ("ART 213", "Visual Concepts IV/Time-Based Media");
INSERT INTO course (course_id, title) VALUES ("ART 214", "Drawing I/Beginning Drawing");
INSERT INTO course (course_id, title) VALUES ("ART 215", "Introduction to Art and Media Studies");
INSERT INTO course (course_id, title) VALUES ("ART 216", "Studies in Visual Culture (Prehistory through the 1750s)");
INSERT INTO course (course_id, title) VALUES ("ART 305", "Moving Images I");
INSERT INTO course (course_id, title) VALUES ("ART 320", "Introduction to Printmaking");
INSERT INTO course (course_id, title) VALUES ("ART 321", "From the Enlightenment to the Birth of Modernism (1750-1880)");
INSERT INTO course (course_id, title) VALUES ("ART 325", "History of Film and Video: 1965 to Present");
INSERT INTO course (course_id, title) VALUES ("ART 327", "Contemporary Directions in Photography");
INSERT INTO course (course_id, title) VALUES ("ART 328", "Postmodernism (1960 - present)");
INSERT INTO course (course_id, title) VALUES ("ART 329", "Topics in Art History and Visual Culture");
INSERT INTO course (course_id, title) VALUES ("ART 331", "Graphic Design I: Image, Sign and Symbol");
INSERT INTO course (course_id, title) VALUES ("ART 332", "Design and Technology I: Print");
INSERT INTO course (course_id, title) VALUES ("ART 333", "Typography I");
INSERT INTO course (course_id, title) VALUES ("ART 334", "Graphic Design IV: Word and Image");
INSERT INTO course (course_id, title) VALUES ("ART 336", "Design and Technology II: Screen");
INSERT INTO course (course_id, title) VALUES ("ART 337", "Typography II");
INSERT INTO course (course_id, title) VALUES ("ART 338", "Motion Design");
INSERT INTO course (course_id, title) VALUES ("ART 341", "Introduction to Animation");
INSERT INTO course (course_id, title) VALUES ("ART 343", "History of Animation");
INSERT INTO course (course_id, title) VALUES ("ART 347", "Writing for Media Arts");
INSERT INTO course (course_id, title) VALUES ("ART 361", "Digital Darkroom");
INSERT INTO course (course_id, title) VALUES ("ART 362", "Black and White Photography");
INSERT INTO course (course_id, title) VALUES ("ART 369", "Topics in Photography");
INSERT INTO course (course_id, title) VALUES ("ART 370", "Silkscreen Printing");
INSERT INTO course (course_id, title) VALUES ("ART 376", "Origins and Issues of Print Media");
INSERT INTO course (course_id, title) VALUES ("ART 380", "History and Theory of Games");
INSERT INTO course (course_id, title) VALUES ("ART 383", "Sound Design");
INSERT INTO course (course_id, title) VALUES ("ART 384", "Introduction to 3D Computer Animation");
INSERT INTO course (course_id, title) VALUES ("ART 387", "Animation in the Physical World");
INSERT INTO course (course_id, title) VALUES ("ART 392", "Topics in Art or Media I");
INSERT INTO course (course_id, title) VALUES ("ART 395", "Television Production Techniques I");
INSERT INTO course (course_id, title) VALUES ("ART 429", "Seminar in Art History & Visual Culture");
INSERT INTO course (course_id, title) VALUES ("ART 430", "Typography III");
INSERT INTO course (course_id, title) VALUES ("ART 431", "Graphic Design III: Human Environmental Design");
INSERT INTO course (course_id, title) VALUES ("ART 434", "Advanced Interface Design");
INSERT INTO course (course_id, title) VALUES ("ART 435", "Topics in Film/Video");
INSERT INTO course (course_id, title) VALUES ("ART 447", "Motion Graphics and Compositing");
INSERT INTO course (course_id, title) VALUES ("ART 460", "Installation Art");
INSERT INTO course (course_id, title) VALUES ("ART 484", "Advanced 3D Animation");
INSERT INTO course (course_id, title) VALUES ("ART 486", "Real Time Animation");
INSERT INTO course (course_id, title) VALUES ("ART 488", "Advanced Topics in Animation");
INSERT INTO course (course_id, title) VALUES ("ART 489", "SENIOR PROJECTS");
INSERT INTO course (course_id, title) VALUES ("ASIA 214", "Focused Cultural Study: South Asia");
INSERT INTO course (course_id, title) VALUES ("ASIA 300", "Topics in Asian Studies");
INSERT INTO course (course_id, title) VALUES ("BIOL 123", "Human Genetics");
INSERT INTO course (course_id, title) VALUES ("BIOL 141", "Foundations of Biology: Cells, Energy and Organisms");
INSERT INTO course (course_id, title) VALUES ("BIOL 142", "Foundations of Biology: Ecology and Evolution");
INSERT INTO course (course_id, title) VALUES ("BIOL 251", "Human Anatomy and Physiology I");
INSERT INTO course (course_id, title) VALUES ("BIOL 251L", "Human Anatomy and Physiology I Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 252", "Human Anatomy and Physiology II");
INSERT INTO course (course_id, title) VALUES ("BIOL 252L", "Human Anatomy and Physiology II Laboratory.");
INSERT INTO course (course_id, title) VALUES ("BIOL 275", "Microbiology");
INSERT INTO course (course_id, title) VALUES ("BIOL 275L", "Microbiology Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 300L", "Experimental Biology Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 302", "Molecular and General Genetics");
INSERT INTO course (course_id, title) VALUES ("BIOL 302L", "Molecular and General Genetics Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 303", "Cell Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 303L", "Cell Biology Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 305L", "Physiology Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 307", "Human Physiology");
INSERT INTO course (course_id, title) VALUES ("BIOL 313", "Introduction to Bioinformatics and Computational Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 316L", "Phage Hunters Genome Analysis");
INSERT INTO course (course_id, title) VALUES ("BIOL 340L", "Developmental Biology Laboratory");
INSERT INTO course (course_id, title) VALUES ("BIOL 395", "MARC U*STAR Writing in the Sciences");
INSERT INTO course (course_id, title) VALUES ("BIOL 397", "Ethics and Integrity in Scientific Research");
INSERT INTO course (course_id, title) VALUES ("BIOL 412", "Microbial Systems and Synthetic Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 414", "Eukaryotic Molecular Genetics");
INSERT INTO course (course_id, title) VALUES ("BIOL 415", "Systems Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 420", "Advanced Topics in Cell Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 425", "Immunology");
INSERT INTO course (course_id, title) VALUES ("BIOL 430", "Biological Chemistry");
INSERT INTO course (course_id, title) VALUES ("BIOL 454", "Vision Science");
INSERT INTO course (course_id, title) VALUES ("BIOL 456", "Plant Molecular Biology");
INSERT INTO course (course_id, title) VALUES ("BIOL 486", "Genome Science");
INSERT INTO course (course_id, title) VALUES ("BIOL 495", "Seminar in Bioinformatics");
INSERT INTO course (course_id, title) VALUES ("BIOL 499L", "Undergraduate Research Seminar");
INSERT INTO course (course_id, title) VALUES ("CHEM 100", "The Chemical World");
INSERT INTO course (course_id, title) VALUES ("CHEM 101", "Principles of Chemistry I");
INSERT INTO course (course_id, title) VALUES ("CHEM 102", "Principles of Chemistry II");
INSERT INTO course (course_id, title) VALUES ("CHEM 102H", "Principles of Chemistry - Honors");
INSERT INTO course (course_id, title) VALUES ("CHEM 102L", "Introductory Chemistry Lab I");
INSERT INTO course (course_id, title) VALUES ("CHEM 124", "Introduction to General Organic and Biochemistry II");
INSERT INTO course (course_id, title) VALUES ("CHEM 124L", "General Organic and Biochemistry Lab");
INSERT INTO course (course_id, title) VALUES ("CHEM 300", "Analytical Chemistry");
INSERT INTO course (course_id, title) VALUES ("CHEM 302", "Physical Chemistry II");
INSERT INTO course (course_id, title) VALUES ("CHEM 303", "Physical Chemistry for the Biochemical Sciences");
INSERT INTO course (course_id, title) VALUES ("CHEM 312L", "Advanced Laboratory II.");
INSERT INTO course (course_id, title) VALUES ("CHEM 351", "Organic Chemistry I");
INSERT INTO course (course_id, title) VALUES ("CHEM 351L", "Organic Chemistry Laboratory I");
INSERT INTO course (course_id, title) VALUES ("CHEM 352", "Organic Chemistry II");
INSERT INTO course (course_id, title) VALUES ("CHEM 352L", "Organic Chemistry Laboratory II");
INSERT INTO course (course_id, title) VALUES ("CHEM 401", "Chemical and Statistical Thermodynamics");
INSERT INTO course (course_id, title) VALUES ("CHEM 437L", "Biochemistry Laboratory");
INSERT INTO course (course_id, title) VALUES ("CHEM 438", "Comprehensive Biochemistry II");
INSERT INTO course (course_id, title) VALUES ("CHEM 455", "Introduction to Biomedicinal Chemistry");
INSERT INTO course (course_id, title) VALUES ("CHEM 461", "Advanced Instrumental Methods of Analysis");
INSERT INTO course (course_id, title) VALUES ("CHEM 490", "Special Topics in Chemistry");
INSERT INTO course (course_id, title) VALUES ("CHIN 102", "Elementary Chinese II");
INSERT INTO course (course_id, title) VALUES ("CHIN 201", "Intermediate Chinese I");
INSERT INTO course (course_id, title) VALUES ("CHIN 202", "Intermediate Chinese II");
INSERT INTO course (course_id, title) VALUES ("CHIN 302", "Advanced Chinese II");
INSERT INTO course (course_id, title) VALUES ("CHIN 319", "Chinese Translation");
INSERT INTO course (course_id, title) VALUES ("CMPE 212", "Principles of Digital Design");
INSERT INTO course (course_id, title) VALUES ("CMPE 306", "Introductory Circuit Theory");
INSERT INTO course (course_id, title) VALUES ("CMPE 310", "Systems Design and Programming");
INSERT INTO course (course_id, title) VALUES ("CMPE 314", "Principles of Eletronic Circuits");
INSERT INTO course (course_id, title) VALUES ("CMPE 315", "Principles of VLSI Design");
INSERT INTO course (course_id, title) VALUES ("CMPE 320", "Probability, Statistics, and Random Processes");
INSERT INTO course (course_id, title) VALUES ("CMPE 330", "Electromagnetic Waves and Transmission");
INSERT INTO course (course_id, title) VALUES ("CMPE 349", "Introduction to Professional Practice");
INSERT INTO course (course_id, title) VALUES ("CMPE 415", "Programmable Logic Devices");
INSERT INTO course (course_id, title) VALUES ("CMPE 418", "VLSI Design Verification and Testing");
INSERT INTO course (course_id, title) VALUES ("CMPE 419", "Computer Arithmetic Algorithms and Implementations");
INSERT INTO course (course_id, title) VALUES ("CMPE 422", "Digital Signal Processing");
INSERT INTO course (course_id, title) VALUES ("CMPE 451", "Capstone II");
INSERT INTO course (course_id, title) VALUES ("CMPE 491", "Special Topics in Computer Engineering");
INSERT INTO course (course_id, title) VALUES ("CMSC 104", "Problem Solving and Computer Programming");
INSERT INTO course (course_id, title) VALUES ("CMSC 201", "Computer Science I for Majors");
INSERT INTO course (course_id, title) VALUES ("CMSC 202", "Computer Science II for Majors");
INSERT INTO course (course_id, title) VALUES ("CMSC 203", "Discrete Structures");
INSERT INTO course (course_id, title) VALUES ("CMSC 304", "Social and Ethical Issues in Information Technology");
INSERT INTO course (course_id, title) VALUES ("CMSC 313", "Computer Organization and Assembly Language Programming");
INSERT INTO course (course_id, title) VALUES ("CMSC 331", "Principles of Programming Language");
INSERT INTO course (course_id, title) VALUES ("CMSC 341", "Data Structures");
INSERT INTO course (course_id, title) VALUES ("CMSC 352", "Women, Gender, and Information Technology");
INSERT INTO course (course_id, title) VALUES ("CMSC 411", "Computer Architecture");
INSERT INTO course (course_id, title) VALUES ("CMSC 421", "Principles of Operating Systems");
INSERT INTO course (course_id, title) VALUES ("CMSC 426", "Principles of Computer Security");
INSERT INTO course (course_id, title) VALUES ("CMSC 433", "Scripting Languages");
INSERT INTO course (course_id, title) VALUES ("CMSC 435", "Computer Graphics");
INSERT INTO course (course_id, title) VALUES ("CMSC 441", "Design and Analysis of Algorithms.");
INSERT INTO course (course_id, title) VALUES ("CMSC 443", "Cryptology");
INSERT INTO course (course_id, title) VALUES ("CMSC 447", "Software Engineering I");
INSERT INTO course (course_id, title) VALUES ("CMSC 453", "Applied Combinatorics and Graph Theory");
INSERT INTO course (course_id, title) VALUES ("CMSC 461", "Database Management Systems");
INSERT INTO course (course_id, title) VALUES ("CMSC 471", "Introduction to Artificial Intelligence");
INSERT INTO course (course_id, title) VALUES ("CMSC 473", "Introduction to Natural Language Processing");
INSERT INTO course (course_id, title) VALUES ("CMSC 478", "Introduction to Machine Learning");
INSERT INTO course (course_id, title) VALUES ("CMSC 481", "Computer Networks");
INSERT INTO course (course_id, title) VALUES ("CMSC 483", "Parallel and Distributed Processing");
INSERT INTO course (course_id, title) VALUES ("CMSC 487", "Introduction To Network Security");
INSERT INTO course (course_id, title) VALUES ("CMSC 491", "Special Topics in Computer Science");
INSERT INTO course (course_id, title) VALUES ("CMSC 493", "Capstone Games Group Project");
INSERT INTO course (course_id, title) VALUES ("DANC 110", "Beginning Contemporary Dance Technique I");
INSERT INTO course (course_id, title) VALUES ("DANC 201", "Dance History I: Cultural and Classical Forms");
INSERT INTO course (course_id, title) VALUES ("DANC 216", "Ballet II--Intermediate Ballet");
INSERT INTO course (course_id, title) VALUES ("DANC 240", "Music for Dance");
INSERT INTO course (course_id, title) VALUES ("DANC 260", "Introduction to African Dance");
INSERT INTO course (course_id, title) VALUES ("DANC 290", "Independent Projects in Choreography");
INSERT INTO course (course_id, title) VALUES ("DANC 301", "Special Studies in Dance");
INSERT INTO course (course_id, title) VALUES ("DANC 310", "Intermediate Contemporary Dance Technique I");
INSERT INTO course (course_id, title) VALUES ("DANC 315", "Beyond Technique: The Body and Motion");
INSERT INTO course (course_id, title) VALUES ("DANC 316", "Ballet III - High Intermediate Ballet");
INSERT INTO course (course_id, title) VALUES ("DANC 320", "Intermediate Contemporary Dance Technique II");
INSERT INTO course (course_id, title) VALUES ("DANC 325", "Dance and the Contemporary Arts");
INSERT INTO course (course_id, title) VALUES ("DANC 330", "Dance Composition I");
INSERT INTO course (course_id, title) VALUES ("DANC 340", "Dance and Technology");
INSERT INTO course (course_id, title) VALUES ("DANC 399", "Dance Practicum");
INSERT INTO course (course_id, title) VALUES ("DANC 416", "Ballet IV - Advanced Ballet");
INSERT INTO course (course_id, title) VALUES ("DANC 420", "Advanced Contemporary Dance Technique II");
INSERT INTO course (course_id, title) VALUES ("DANC 475", "Senior Projects in Dance");
INSERT INTO course (course_id, title) VALUES ("ECAC 317", "Accounting Information Systems");
INSERT INTO course (course_id, title) VALUES ("ECAC 321", "Auditing Theory and Practice");
INSERT INTO course (course_id, title) VALUES ("ECAC 330", "Principles of Taxation");
INSERT INTO course (course_id, title) VALUES ("ECAC 401", "Advanced Accounting");
INSERT INTO course (course_id, title) VALUES ("ECON 101", "Principles of Microeconomics");
INSERT INTO course (course_id, title) VALUES ("ECON 102", "Principles of Macroeconomics");
INSERT INTO course (course_id, title) VALUES ("ECON 121", "Principles of Accounting I");
INSERT INTO course (course_id, title) VALUES ("ECON 122", "Principles of Accounting II");
INSERT INTO course (course_id, title) VALUES ("ECON 301", "Intermediate Accounting I");
INSERT INTO course (course_id, title) VALUES ("ECON 302", "Intermediate Accounting II");
INSERT INTO course (course_id, title) VALUES ("ECON 311", "Intermediate Microeconomic Analysis");
INSERT INTO course (course_id, title) VALUES ("ECON 312", "Intermediate Macroeconomic Analysis");
INSERT INTO course (course_id, title) VALUES ("ECON 320", "Quantitative Methods for Management");
INSERT INTO course (course_id, title) VALUES ("ECON 374", "Financial Management");
INSERT INTO course (course_id, title) VALUES ("ECON 405", "Benefit-Cost Evaluation");
INSERT INTO course (course_id, title) VALUES ("ECON 408", "Managerial Economics");
INSERT INTO course (course_id, title) VALUES ("ECON 421", "Introduction to Econometrics");
INSERT INTO course (course_id, title) VALUES ("ECON 423", "Economic Forecasting");
INSERT INTO course (course_id, title) VALUES ("ECON 437", "The Economics of Natural Resources");
INSERT INTO course (course_id, title) VALUES ("ECON 443", "History of Economic Thought");
INSERT INTO course (course_id, title) VALUES ("ECON 451", "Labor Economics");
INSERT INTO course (course_id, title) VALUES ("ECON 467", "Health Economics");
INSERT INTO course (course_id, title) VALUES ("ECON 471", "Financial Markets and Institutions");
INSERT INTO course (course_id, title) VALUES ("ECON 474", "Intermediate Financial Management");
INSERT INTO course (course_id, title) VALUES ("ECON 475", "Financial Investment Analysis");
INSERT INTO course (course_id, title) VALUES ("ECON 478", "Real Estate Economics and Finance");
INSERT INTO course (course_id, title) VALUES ("ECON 482", "International Finance");
INSERT INTO course (course_id, title) VALUES ("EDUC 216", "Foundations of Leadership Development");
INSERT INTO course (course_id, title) VALUES ("EDUC 299", "Special Topics in Education.");
INSERT INTO course (course_id, title) VALUES ("EDUC 306", "Lifespan Human Development");
INSERT INTO course (course_id, title) VALUES ("EDUC 310", "Inquiry into Education");
INSERT INTO course (course_id, title) VALUES ("EDUC 311", "Psychological Foundations of Education");
INSERT INTO course (course_id, title) VALUES ("EDUC 313", "Concepts and Practice of Peer-Assisted Learning I");
INSERT INTO course (course_id, title) VALUES ("EDUC 388", "Inclusion and Instruction");
INSERT INTO course (course_id, title) VALUES ("EDUC 410", "Teaching Reading in the Content Areas: Part I");
INSERT INTO course (course_id, title) VALUES ("EDUC 412", "Analysis of Teaching and Learning");
INSERT INTO course (course_id, title) VALUES ("EDUC 414", "Adolescent Literature");
INSERT INTO course (course_id, title) VALUES ("EDUC 416", "Materials for Teaching Reading");
INSERT INTO course (course_id, title) VALUES ("EDUC 417", "Processes and Acquisition of Reading");
INSERT INTO course (course_id, title) VALUES ("EDUC 418", "Instruction of Reading");
INSERT INTO course (course_id, title) VALUES ("EDUC 419", "Assessment for Reading Instruction");
INSERT INTO course (course_id, title) VALUES ("EDUC 420", "Teaching Mathematics in the Elementary School");
INSERT INTO course (course_id, title) VALUES ("EDUC 433", "Mathematics Processes in Early Childhood Education");
INSERT INTO course (course_id, title) VALUES ("EDUC 439", "Observation and Assessment in Early Childhood");
INSERT INTO course (course_id, title) VALUES ("EDUC 441", "Children's Literature and Other Materials for Early Literacy Development");
INSERT INTO course (course_id, title) VALUES ("EDUC 442", "Process Seminar in Early Childhood Education- Creative Media Level I");
INSERT INTO course (course_id, title) VALUES ("EDUC 447", "Teaching of Reading and Writing in Early Childhood Education");
INSERT INTO course (course_id, title) VALUES ("EDUC 453", "Elementary Internship Seminar");
INSERT INTO course (course_id, title) VALUES ("EDUC 457", "Secondary Internship Seminar");
INSERT INTO course (course_id, title) VALUES ("EHS 102", "Emergency Medical Responder");
INSERT INTO course (course_id, title) VALUES ("EHS 200", "Concepts of Emergency Health Services");
INSERT INTO course (course_id, title) VALUES ("EHS 203", "Clinical Concepts and Practice II");
INSERT INTO course (course_id, title) VALUES ("EHS 311", "Stress and Burnout: Personal and Professional Issues");
INSERT INTO course (course_id, title) VALUES ("EHS 330", "Management of Search and Rescue Operations");
INSERT INTO course (course_id, title) VALUES ("EHS 345", "Death and Dying");
INSERT INTO course (course_id, title) VALUES ("EHS 350", "Supervision and Operations in Emergency Health Service Systems");
INSERT INTO course (course_id, title) VALUES ("EHS 351", "Financial Management, Budgeting and Resource Allocation for Emergency Health Administrators.");
INSERT INTO course (course_id, title) VALUES ("EHS 360", "Instructional Issues in Emergency Health Services");
INSERT INTO course (course_id, title) VALUES ("EHS 400", "Emergency Health Services Theory and Practice");
INSERT INTO course (course_id, title) VALUES ("EHS 464", "Advanced Cardiac and Respiratory Emergencies");
INSERT INTO course (course_id, title) VALUES ("EHS 465", "Medical Emergencies I");
INSERT INTO course (course_id, title) VALUES ("EHS 466", "Medical Emergencies II");
INSERT INTO course (course_id, title) VALUES ("EHS 468", "EMS Capstone Experience");
INSERT INTO course (course_id, title) VALUES ("EHS 482", "ALS Field and Clinical Experience II");
INSERT INTO course (course_id, title) VALUES ("EHS 484", "Advanced Cardiac & Respiratory Emergencies");
INSERT INTO course (course_id, title) VALUES ("EHS 492", "Senior Paramedic Seminar II");
INSERT INTO course (course_id, title) VALUES ("EHS 498", "Financial Management and Decision Support for Health Service Organizations");
INSERT INTO course (course_id, title) VALUES ("ELC 41", "Writing and Grammar for Academic Purposes, Level 4");
INSERT INTO course (course_id, title) VALUES ("ELC 42", "Reading and Vocabulary for Academic Purposes, Level 4");
INSERT INTO course (course_id, title) VALUES ("ELC 43", "Speaking and Listening for Academic Purposes, Level 4");
INSERT INTO course (course_id, title) VALUES ("ELC 51", "Advanced Writing and Grammar for Academic Purposes, Level 5");
INSERT INTO course (course_id, title) VALUES ("ELC 52", "Advanced Reading and Vocabulary for Academic Purposes, Level 5");
INSERT INTO course (course_id, title) VALUES ("ELC 53", "Speaking and Listening for Academic Purposes, Level 5");
INSERT INTO course (course_id, title) VALUES ("ELC 61", "Writing for Research and Professional Purposes, Level 6");
INSERT INTO course (course_id, title) VALUES ("ELC 63", "Speaking and Listening for Research and Professional Purposes, Level 6");
INSERT INTO course (course_id, title) VALUES ("ENCH 225L", "Chemical Engineering Problem Solving and Experimental Design Lab");
INSERT INTO course (course_id, title) VALUES ("ENCH 333", "Chemical Engineering Seminar");
INSERT INTO course (course_id, title) VALUES ("ENCH 412", "Environmental Physicochemical Processes");
INSERT INTO course (course_id, title) VALUES ("ENCH 427", "Transport Processes II: Mass Transfer");
INSERT INTO course (course_id, title) VALUES ("ENCH 440", "Chemical Engineering Kinetics.");
INSERT INTO course (course_id, title) VALUES ("ENCH 442", "Chemical Process Control & Safety");
INSERT INTO course (course_id, title) VALUES ("ENCH 446", "Process Engineering Economics and Design II.");
INSERT INTO course (course_id, title) VALUES ("ENCH 450", "Chemical Process Development");
INSERT INTO course (course_id, title) VALUES ("ENCH 476", "Environmental Risk Assessment & Remediation");
INSERT INTO course (course_id, title) VALUES ("ENCH 484", "Biomedical Engineering");
INSERT INTO course (course_id, title) VALUES ("ENCH 485L", "Biochemical Engineering Laboratory.");
INSERT INTO course (course_id, title) VALUES ("ENES 100", "Spatial Reasoning");
INSERT INTO course (course_id, title) VALUES ("ENES 101", "Introduction to Engineering");
INSERT INTO course (course_id, title) VALUES ("ENGL 100", "Composition");
INSERT INTO course (course_id, title) VALUES ("ENGL 110", "Composition for ESL Students");
INSERT INTO course (course_id, title) VALUES ("ENGL 190", "The World of Language I");
INSERT INTO course (course_id, title) VALUES ("ENGL 191", "The World of Language II");
INSERT INTO course (course_id, title) VALUES ("ENGL 210", "Introduction to Literature");
INSERT INTO course (course_id, title) VALUES ("ENGL 226", "Grammar and Usage of Standard English");
INSERT INTO course (course_id, title) VALUES ("ENGL 233", "Issues in World Literature");
INSERT INTO course (course_id, title) VALUES ("ENGL 261", "Black Literature: Twentieth Century");
INSERT INTO course (course_id, title) VALUES ("ENGL 271", "Introduction to Creative Writing - Fiction");
INSERT INTO course (course_id, title) VALUES ("ENGL 273", "Introduction to Creative Writing - Poetry");
INSERT INTO course (course_id, title) VALUES ("ENGL 291", "Introduction to Writing Creative Essays");
INSERT INTO course (course_id, title) VALUES ("ENGL 300", "Texts and Contexts");
INSERT INTO course (course_id, title) VALUES ("ENGL 301", "Analysis of Literary Language");
INSERT INTO course (course_id, title) VALUES ("ENGL 302", "Literary Methodologies and Research");
INSERT INTO course (course_id, title) VALUES ("ENGL 303", "The Art of the Essay");
INSERT INTO course (course_id, title) VALUES ("ENGL 304", "British Literature: Medieval and Renaissance");
INSERT INTO course (course_id, title) VALUES ("ENGL 306", "British Literature: Victorian and Modern");
INSERT INTO course (course_id, title) VALUES ("ENGL 307", "American Literature: from New World Contact to the Civil War");
INSERT INTO course (course_id, title) VALUES ("ENGL 308", "American Literature: The Civil War to 1945");
INSERT INTO course (course_id, title) VALUES ("ENGL 317", "Literature and the Sciences");
INSERT INTO course (course_id, title) VALUES ("ENGL 321", "Internship in Tutoring Writing");
INSERT INTO course (course_id, title) VALUES ("ENGL 324", "Theories of Communication and Technology");
INSERT INTO course (course_id, title) VALUES ("ENGL 326", "The Structure of English");
INSERT INTO course (course_id, title) VALUES ("ENGL 360", "The Literature of Minorities");
INSERT INTO course (course_id, title) VALUES ("ENGL 373", "Creative Writing-Poetry");
INSERT INTO course (course_id, title) VALUES ("ENGL 375", "Masterworks for Creative Writers");
INSERT INTO course (course_id, title) VALUES ("ENGL 382", "Feature Writing");
INSERT INTO course (course_id, title) VALUES ("ENGL 383", "Science Writing");
INSERT INTO course (course_id, title) VALUES ("ENGL 385", "New Media and Digital Literacies");
INSERT INTO course (course_id, title) VALUES ("ENGL 391", "Advanced Exposition and Argumentation");
INSERT INTO course (course_id, title) VALUES ("ENGL 392", "Tutorial in Writing");
INSERT INTO course (course_id, title) VALUES ("ENGL 393", "Technical Communication");
INSERT INTO course (course_id, title) VALUES ("ENGL 405", "Seminar in Literary History");
INSERT INTO course (course_id, title) VALUES ("ENGL 407", "Language in Society");
INSERT INTO course (course_id, title) VALUES ("ENGL 411", "Advanced Topics in Literary History");
INSERT INTO course (course_id, title) VALUES ("ENGL 414", "Adolescent Literature");
INSERT INTO course (course_id, title) VALUES ("ENGL 415", "Materials for Teaching Reading");
INSERT INTO course (course_id, title) VALUES ("ENGL 448", "Seminar in Literature and Culture");
INSERT INTO course (course_id, title) VALUES ("ENGL 464", "Studies in Women and Literature");
INSERT INTO course (course_id, title) VALUES ("ENGL 471", "Advanced Creative Writing-Fiction");
INSERT INTO course (course_id, title) VALUES ("ENGL 480", "Seminar in Advanced Journalism");
INSERT INTO course (course_id, title) VALUES ("ENGL 493", "Seminar in Communication and Technology");
INSERT INTO course (course_id, title) VALUES ("ENME 110", "Statics");
INSERT INTO course (course_id, title) VALUES ("ENME 204", "Introduction to Engineering Design with CAD");
INSERT INTO course (course_id, title) VALUES ("ENME 217", "Engineering Thermodynamics ");
INSERT INTO course (course_id, title) VALUES ("ENME 220", "Mechanics of Materials");
INSERT INTO course (course_id, title) VALUES ("ENME 221", "Dynamics");
INSERT INTO course (course_id, title) VALUES ("ENME 301", "The Structure and Properties of Engineering Materials");
INSERT INTO course (course_id, title) VALUES ("ENME 303", "Topics in Engineering Mathematics");
INSERT INTO course (course_id, title) VALUES ("ENME 304", "Machine Design");
INSERT INTO course (course_id, title) VALUES ("ENME 320", "Fluid Mechanics");
INSERT INTO course (course_id, title) VALUES ("ENME 321", "Transfer Processes");
INSERT INTO course (course_id, title) VALUES ("ENME 332L", "Solid Mechanics and Materials Laboratory");
INSERT INTO course (course_id, title) VALUES ("ENME 360", "Vibrations");
INSERT INTO course (course_id, title) VALUES ("ENME 403", "Automatic Controls.");
INSERT INTO course (course_id, title) VALUES ("ENME 408", "Selected Topics in Engineering Design");
INSERT INTO course (course_id, title) VALUES ("ENME 425", "Internal Combustion Engines");
INSERT INTO course (course_id, title) VALUES ("ENME 432L", "Fluids/Energy Laboratory");
INSERT INTO course (course_id, title) VALUES ("ENME 444", "Mechanical Engineering Systems Design");
INSERT INTO course (course_id, title) VALUES ("ENME 482L", "Vibrations/Controls Laboratory");
INSERT INTO course (course_id, title) VALUES ("ENME 489", "Special Topics in Mechanical Engineering");
INSERT INTO course (course_id, title) VALUES ("ENTR 200", "Introduction to Entrepreneurship");
INSERT INTO course (course_id, title) VALUES ("ENTR 201", "The Entrepreneurial Mindset");
INSERT INTO course (course_id, title) VALUES ("ENTR 320", "Entrepreneurial Marketing");
INSERT INTO course (course_id, title) VALUES ("ENTR 340", "Innovation, Creative Problem-Solving & the Socialpreneur");
INSERT INTO course (course_id, title) VALUES ("FREN 101", "Elementary French I");
INSERT INTO course (course_id, title) VALUES ("FREN 102", "Elementary French II");
INSERT INTO course (course_id, title) VALUES ("FREN 103", "Intensive Review of Elementary French");
INSERT INTO course (course_id, title) VALUES ("FREN 201", "Intermediate French I");
INSERT INTO course (course_id, title) VALUES ("FREN 202", "Intermediate French II");
INSERT INTO course (course_id, title) VALUES ("FREN 301", "Advanced French I");
INSERT INTO course (course_id, title) VALUES ("FREN 302", "Advanced French II");
INSERT INTO course (course_id, title) VALUES ("FREN 315", "French Phonetics");
INSERT INTO course (course_id, title) VALUES ("FREN 320", "Interconnections: Trade, Technology, and Globalization");
INSERT INTO course (course_id, title) VALUES ("FREN 330", "Interconnections: Ideas, Literature and the Arts");
INSERT INTO course (course_id, title) VALUES ("FREN 440", "Studies in French Speaking Culture and Society");
INSERT INTO course (course_id, title) VALUES ("FYS 101", "First Year Seminar (AH)");
INSERT INTO course (course_id, title) VALUES ("FYS 101Y", "First Year Seminar (AH)");
INSERT INTO course (course_id, title) VALUES ("FYS 102", "First Year Seminar (SS)");
INSERT INTO course (course_id, title) VALUES ("FYS 107", "First Year Seminar (AH/C)");
INSERT INTO course (course_id, title) VALUES ("GCSP 302", "Grand Challenges Program Seminar");
INSERT INTO course (course_id, title) VALUES ("GERM 101", "Elementary German I");
INSERT INTO course (course_id, title) VALUES ("GERM 102", "Elementary German II");
INSERT INTO course (course_id, title) VALUES ("GERM 201", "Intermediate German I");
INSERT INTO course (course_id, title) VALUES ("GERM 202", "Gateway to Advanced German Studies");
INSERT INTO course (course_id, title) VALUES ("GERM 302", "Advanced German Studies II (L)");
INSERT INTO course (course_id, title) VALUES ("GERM 375", "Germany Then and Now: Explorations of German Cultural and Intellectual History.");
INSERT INTO course (course_id, title) VALUES ("GERM 481", "Seminar in Intercultural German Studies");
INSERT INTO course (course_id, title) VALUES ("GES 102", "Human Geography");
INSERT INTO course (course_id, title) VALUES ("GES 110", "Physical Geography");
INSERT INTO course (course_id, title) VALUES ("GES 120", "Environmental Science and Conservation");
INSERT INTO course (course_id, title) VALUES ("GES 220", "Lab and Field Techniques for Environmental Science");
INSERT INTO course (course_id, title) VALUES ("GES 286", "Exploring the Environment: A Geo-Spatial Perspective");
INSERT INTO course (course_id, title) VALUES ("GES 302", "Selective Topics in Geography");
INSERT INTO course (course_id, title) VALUES ("GES 307", "Conservation Biology");
INSERT INTO course (course_id, title) VALUES ("GES 310", "Geomorphology");
INSERT INTO course (course_id, title) VALUES ("GES 338", "Chesapeake Bay: Changing Management & Policy");
INSERT INTO course (course_id, title) VALUES ("GES 341", "Urban Geography");
INSERT INTO course (course_id, title) VALUES ("GES 383", "Statistical and Thematic Cartography");
INSERT INTO course (course_id, title) VALUES ("GES 386", "Introduction to Geographic Information Systems");
INSERT INTO course (course_id, title) VALUES ("GES 400", "Selected Topics In Geography");
INSERT INTO course (course_id, title) VALUES ("GES 406", "Aquatic Ecology");
INSERT INTO course (course_id, title) VALUES ("GES 413", "Seminar in Biogeography");
INSERT INTO course (course_id, title) VALUES ("GES 419", "Watershed Analysis & Modeling");
INSERT INTO course (course_id, title) VALUES ("GES 429", "Seminar in Geography of Disease and Health");
INSERT INTO course (course_id, title) VALUES ("GES 462", "GIS and Human-Environmental Systems");
INSERT INTO course (course_id, title) VALUES ("GES 488", "Spatial Data Analysis and GIS Applications");
INSERT INTO course (course_id, title) VALUES ("GLBL 101", "Introduction to Global Studies");
INSERT INTO course (course_id, title) VALUES ("GLBL 301", "Approaches to Globalization");
INSERT INTO course (course_id, title) VALUES ("GREK 102", "Elementary Greek II");
INSERT INTO course (course_id, title) VALUES ("GREK 362", "Selections from Greek Historians");
INSERT INTO course (course_id, title) VALUES ("GWST 100", "Introduction to Gender and Women's Studies");
INSERT INTO course (course_id, title) VALUES ("GWST 200", "Studies in Feminist Activism");
INSERT INTO course (course_id, title) VALUES ("GWST 210", "Introduction to Critical Sexuality Studies");
INSERT INTO course (course_id, title) VALUES ("GWST 300", "Methodologies in Gender, Women's, and Sexuality Studies");
INSERT INTO course (course_id, title) VALUES ("GWST 321", "Queer Representation in Film and TV");
INSERT INTO course (course_id, title) VALUES ("GWST 322", "Gender, Race, and Media");
INSERT INTO course (course_id, title) VALUES ("GWST 333", "Human Sexuality in Cross-Cultural Perspective");
INSERT INTO course (course_id, title) VALUES ("GWST 338", "Women, Gender, and Law");
INSERT INTO course (course_id, title) VALUES ("GWST 340", "Women, Gender and Globalization");
INSERT INTO course (course_id, title) VALUES ("GWST 352", "Women, Gender, and Information Technology");
INSERT INTO course (course_id, title) VALUES ("GWST 353", "Marriage and the Family");
INSERT INTO course (course_id, title) VALUES ("GWST 357", "Psychology of Women");
INSERT INTO course (course_id, title) VALUES ("GWST 374", "European Women's History 1200-1750");
INSERT INTO course (course_id, title) VALUES ("GWST 380", "Women and Gender in Asia");
INSERT INTO course (course_id, title) VALUES ("GWST 390", "Topics in Gender and Women's Studies");
INSERT INTO course (course_id, title) VALUES ("GWST 392", "Topics in Critical Sexuality Studies");
INSERT INTO course (course_id, title) VALUES ("GWST 433", "Gender, Work, and Family in Cross-Cultural Perspective");
INSERT INTO course (course_id, title) VALUES ("GWST 439", "Women in Africa and the Diaspora");
INSERT INTO course (course_id, title) VALUES ("GWST 464", "Studies in Women and Literature");
INSERT INTO course (course_id, title) VALUES ("GWST 480", "Theories of Feminism");
INSERT INTO course (course_id, title) VALUES ("GWST 485", "Sexuality and Queer Theory");
INSERT INTO course (course_id, title) VALUES ("GWST 495", "Colloquium: Research and Activism");
INSERT INTO course (course_id, title) VALUES ("HAPP 100", "Survey of the US Healthcare System");
INSERT INTO course (course_id, title) VALUES ("HAPP 200", "Human Development Implications for Health and Disease");
INSERT INTO course (course_id, title) VALUES ("HAPP 300", "Research Methods in Health");
INSERT INTO course (course_id, title) VALUES ("HAPP 340", "Health Communication");
INSERT INTO course (course_id, title) VALUES ("HAPP 350", "Public Health Ethics");
INSERT INTO course (course_id, title) VALUES ("HAPP 354", "Social Bases of Public and Community Health");
INSERT INTO course (course_id, title) VALUES ("HAPP 380", "Global Issues in Health and Disease");
INSERT INTO course (course_id, title) VALUES ("HAPP 401", "Occupational Health Policy and Practice");
INSERT INTO course (course_id, title) VALUES ("HAPP 411", "Health Regulation and Quality Improvement");
INSERT INTO course (course_id, title) VALUES ("HAPP 420", "Epidemiology");
INSERT INTO course (course_id, title) VALUES ("HAPP 452", "Health Care Organization and Delivery");
INSERT INTO course (course_id, title) VALUES ("HAPP 470", "Health Administration and Policy Program Internship");
INSERT INTO course (course_id, title) VALUES ("HAPP 498", "Financial Management and Decision Support for Health Service Organizations");
INSERT INTO course (course_id, title) VALUES ("HCST 100", "The Human Context of Science and Technology");
INSERT INTO course (course_id, title) VALUES ("HCST 100H", "Introduction to the Human Context of Science and Technology");
INSERT INTO course (course_id, title) VALUES ("HEBR 102", "Elementary Modern Hebrew II");
INSERT INTO course (course_id, title) VALUES ("HIND 102", "Elementary Hindi II");
INSERT INTO course (course_id, title) VALUES ("HIND 202", "Intermediate Hindi II");
INSERT INTO course (course_id, title) VALUES ("HIST 101", "American History to 1877");
INSERT INTO course (course_id, title) VALUES ("HIST 102", "American History, 1877 to the Present");
INSERT INTO course (course_id, title) VALUES ("HIST 103", "East-Asian Civilization");
INSERT INTO course (course_id, title) VALUES ("HIST 110", "Western Civilization to 1700");
INSERT INTO course (course_id, title) VALUES ("HIST 110H", "Western Civilization to 1700 - Honors");
INSERT INTO course (course_id, title) VALUES ("HIST 111", "Western Civilization 1700 to the Present");
INSERT INTO course (course_id, title) VALUES ("HIST 111Y", "Western Civilization 1700 to the Present");
INSERT INTO course (course_id, title) VALUES ("HIST 200", "Themes in World History");
INSERT INTO course (course_id, title) VALUES ("HIST 201", "Introduction to the Study of History");
INSERT INTO course (course_id, title) VALUES ("HIST 209", "Themes in World History: Planets and Worlds, Earth and Home");
INSERT INTO course (course_id, title) VALUES ("HIST 218", "Introduction to African-American History: A Survey");
INSERT INTO course (course_id, title) VALUES ("HIST 242", "Introduction to Contemporary Africa");
INSERT INTO course (course_id, title) VALUES ("HIST 300", "Introduction to Public History");
INSERT INTO course (course_id, title) VALUES ("HIST 302", "History of Maryland");
INSERT INTO course (course_id, title) VALUES ("HIST 303", "The Second World War");
INSERT INTO course (course_id, title) VALUES ("HIST 306", "The First World War");
INSERT INTO course (course_id, title) VALUES ("HIST 313", "America as a Great Power? U.S.Foreign Relations in the Twentieth Century");
INSERT INTO course (course_id, title) VALUES ("HIST 322", "African American History Since 1865");
INSERT INTO course (course_id, title) VALUES ("HIST 328", "Colonial Latin America");
INSERT INTO course (course_id, title) VALUES ("HIST 347", "The United States Since 1945");
INSERT INTO course (course_id, title) VALUES ("HIST 350", "History of Medicine");
INSERT INTO course (course_id, title) VALUES ("HIST 360", "Islam in Africa");
INSERT INTO course (course_id, title) VALUES ("HIST 364", "The Rise of Islam");
INSERT INTO course (course_id, title) VALUES ("HIST 374", "European Women's History 1200-1750");
INSERT INTO course (course_id, title) VALUES ("HIST 380", "Women and Gender in Asia");
INSERT INTO course (course_id, title) VALUES ("HIST 390", "Wars in 20th Century East Asia");
INSERT INTO course (course_id, title) VALUES ("HIST 411", "Service Learning in Public History");
INSERT INTO course (course_id, title) VALUES ("HIST 413", "American Revolution");
INSERT INTO course (course_id, title) VALUES ("HIST 446", "History of Science Since 1700");
INSERT INTO course (course_id, title) VALUES ("HIST 449", "From Black Power to Black Lives Matter:");
INSERT INTO course (course_id, title) VALUES ("HIST 453", "Ancient Greece");
INSERT INTO course (course_id, title) VALUES ("HIST 463", "Jews, Christians and Muslims in the Middle Ages");
INSERT INTO course (course_id, title) VALUES ("HIST 468", "The Age of Enlightenment");
INSERT INTO course (course_id, title) VALUES ("HIST 472", "Victorian Britain");
INSERT INTO course (course_id, title) VALUES ("HIST 479", "History of China, 1912-1949");
INSERT INTO course (course_id, title) VALUES ("HIST 484", "German History: 1914 to the Present");
INSERT INTO course (course_id, title) VALUES ("HIST 486", "Soviet History on Trial");
INSERT INTO course (course_id, title) VALUES ("HIST 496", "Historical Research");
INSERT INTO course (course_id, title) VALUES ("HIST 497", "Historical Research:");
INSERT INTO course (course_id, title) VALUES ("HONR 211", "Great Books Seminar II");
INSERT INTO course (course_id, title) VALUES ("HONR 300", "General Honors Seminar");
INSERT INTO course (course_id, title) VALUES ("HUM 121H", "Introduction to the Humanities II");
INSERT INTO course (course_id, title) VALUES ("INDS 330", "Ways of Knowing");
INSERT INTO course (course_id, title) VALUES ("INDS 330H", "Ways of Knowing");
INSERT INTO course (course_id, title) VALUES ("INDS 335", "Interdisciplinary Degree Plan Writing Seminar");
INSERT INTO course (course_id, title) VALUES ("INDS 430", "Interdisciplinary Studies Seminar");
INSERT INTO course (course_id, title) VALUES ("INDS 480", "Interdisciplinary Studies:Capstone Project Seminar");
INSERT INTO course (course_id, title) VALUES ("INTR 152", "JHU ROTC: AS.374.102");
INSERT INTO course (course_id, title) VALUES ("INTR 154", "JHU ROTC: AS.374.202");
INSERT INTO course (course_id, title) VALUES ("INTR 157", "JHU ROTC: AS.374.120");
INSERT INTO course (course_id, title) VALUES ("INTR 158", "JHU ROTC: AS.374.220");
INSERT INTO course (course_id, title) VALUES ("INTR 352", "JHU ROTC: AS.374.302");
INSERT INTO course (course_id, title) VALUES ("INTR 354", "JHU ROTC: AS.374.402");
INSERT INTO course (course_id, title) VALUES ("INTR 355", "JHU ROTC: AS.374.307");
INSERT INTO course (course_id, title) VALUES ("INTR 357", "JHU ROTC: AS.374.320");
INSERT INTO course (course_id, title) VALUES ("INTR 359", "JHU ROTC: AS.374.420");
INSERT INTO course (course_id, title) VALUES ("IS 101", "Introduction to Computer Based Systems");
INSERT INTO course (course_id, title) VALUES ("IS 125", "Information Systems Logic and Structured Design");
INSERT INTO course (course_id, title) VALUES ("IS 147", "Introduction to Computer Programming");
INSERT INTO course (course_id, title) VALUES ("IS 202", "Systems Analysis Methods");
INSERT INTO course (course_id, title) VALUES ("IS 246", "Topics in Programming Languages and Tools");
INSERT INTO course (course_id, title) VALUES ("IS 247", "Computer Programming II");
INSERT INTO course (course_id, title) VALUES ("IS 295", "Intermediate Business Applications");
INSERT INTO course (course_id, title) VALUES ("IS 300", "Management Information Systems");
INSERT INTO course (course_id, title) VALUES ("IS 303", "Fundamentals of Human-Computer Interaction");
INSERT INTO course (course_id, title) VALUES ("IS 304", "Ethical Issues in Information Systems");
INSERT INTO course (course_id, title) VALUES ("IS 310", "Software and Hardware Concepts");
INSERT INTO course (course_id, title) VALUES ("IS 317", "Accounting Information Systems");
INSERT INTO course (course_id, title) VALUES ("IS 320", "Advanced Business Applications");
INSERT INTO course (course_id, title) VALUES ("IS 325", "Introduction to Management Science");
INSERT INTO course (course_id, title) VALUES ("IS 350", "Business Communications Systems");
INSERT INTO course (course_id, title) VALUES ("IS 352", "Women, Gender, and Information Technology");
INSERT INTO course (course_id, title) VALUES ("IS 369", "Research Seminar: Writings In Information Systems");
INSERT INTO course (course_id, title) VALUES ("IS 410", "Introduction to Database Design");
INSERT INTO course (course_id, title) VALUES ("IS 413", "GUI Systems Using JAVA");
INSERT INTO course (course_id, title) VALUES ("IS 420", "Database Application Development");
INSERT INTO course (course_id, title) VALUES ("IS 425", "Decision Support Systems");
INSERT INTO course (course_id, title) VALUES ("IS 427", "Introduction to Artificial Intelligence: Concepts and Applications");
INSERT INTO course (course_id, title) VALUES ("IS 430", "Information Systems and Security");
INSERT INTO course (course_id, title) VALUES ("IS 436", "Structured Systems Analysis and Design");
INSERT INTO course (course_id, title) VALUES ("IS 438", "Project Management");
INSERT INTO course (course_id, title) VALUES ("IS 440", "Integrating Technology into Business Processes");
INSERT INTO course (course_id, title) VALUES ("IS 448", "Markup and Scripting Languages");
INSERT INTO course (course_id, title) VALUES ("IS 450", "Data Communications and Networks");
INSERT INTO course (course_id, title) VALUES ("IS 451", "Network Design and Management");
INSERT INTO course (course_id, title) VALUES ("IS 451M", "LAN Management Using Microsoft");
INSERT INTO course (course_id, title) VALUES ("IS 451U", "LAN Management Using Unix");
INSERT INTO course (course_id, title) VALUES ("IS 452", "Internetworking");
INSERT INTO course (course_id, title) VALUES ("IS 471", "Data Analytics for Cybersecurity");
INSERT INTO course (course_id, title) VALUES ("IS 498", "Special Topics in Information Systems");
INSERT INTO course (course_id, title) VALUES ("JDST 201", "Judaism in the Time of Jesus and Hillel");
INSERT INTO course (course_id, title) VALUES ("JDST 290", "Topics in Judaic Studies");
INSERT INTO course (course_id, title) VALUES ("JDST 323", "Modern Hebrew Literature");
INSERT INTO course (course_id, title) VALUES ("JDST 340", "Origins of Antisemitism");
INSERT INTO course (course_id, title) VALUES ("JDST 410", "Dynamics of the Arab-Israeli Conflict");
INSERT INTO course (course_id, title) VALUES ("JDST 463", "Jews, Christians and Muslims in the Middle Ages");
INSERT INTO course (course_id, title) VALUES ("JPNS 102", "Elementary Japanese II");
INSERT INTO course (course_id, title) VALUES ("JPNS 202", "Intermediate Japanese II");
INSERT INTO course (course_id, title) VALUES ("JPNS 302", "Advanced Japanese II");
INSERT INTO course (course_id, title) VALUES ("JPNS 319", "Japanese Translation");
INSERT INTO course (course_id, title) VALUES ("KORE 102", "Elementary Korean II");
INSERT INTO course (course_id, title) VALUES ("KORE 202", "Intermediate Korean II");
INSERT INTO course (course_id, title) VALUES ("KORE 302", "Advanced Korean II");
INSERT INTO course (course_id, title) VALUES ("KORE 310", "Korean Language in Social and Cultural Context");
INSERT INTO course (course_id, title) VALUES ("LAS 121H", "Introduction to the Arts II");
INSERT INTO course (course_id, title) VALUES ("LAS 300", "Collaborative Projects in the Arts");
INSERT INTO course (course_id, title) VALUES ("LATN 102", "Elementary Latin II");
INSERT INTO course (course_id, title) VALUES ("LATN 311", "Roman Poetry: Catullus, Horace");
INSERT INTO course (course_id, title) VALUES ("LING 190", "The World of Language I");
INSERT INTO course (course_id, title) VALUES ("LING 191", "The World of Language II");
INSERT INTO course (course_id, title) VALUES ("LING 210", "Introduction to Language Structures");
INSERT INTO course (course_id, title) VALUES ("LING 230", "World Language Communities");
INSERT INTO course (course_id, title) VALUES ("LING 360", "Sociolinguistics and Dialectology");
INSERT INTO course (course_id, title) VALUES ("LING 410", "Language Planning");
INSERT INTO course (course_id, title) VALUES ("LING 470", "Language and Cognition");
INSERT INTO course (course_id, title) VALUES ("LRC 101A", "Academic Success for Lifelong Learning");
INSERT INTO course (course_id, title) VALUES ("LRC 105", "Academic Success for Lifelong Learning");
INSERT INTO course (course_id, title) VALUES ("LRC 115", "Advanced Diction");
INSERT INTO course (course_id, title) VALUES ("LRC 99", "Introductory Algebra");
INSERT INTO course (course_id, title) VALUES ("MATH 104", "Math Foundations");
INSERT INTO course (course_id, title) VALUES ("MATH 104Y", "Quantitative Literacy");
INSERT INTO course (course_id, title) VALUES ("MATH 106", "Algebra and Elementary Functions");
INSERT INTO course (course_id, title) VALUES ("MATH 120", "Introduction to Contemporary Mathematics");
INSERT INTO course (course_id, title) VALUES ("MATH 132", "Mathematics for Elementary School Teachers II");
INSERT INTO course (course_id, title) VALUES ("MATH 150", "Precalculus Mathematics");
INSERT INTO course (course_id, title) VALUES ("MATH 151", "Calculus and Analytic Geometry I");
INSERT INTO course (course_id, title) VALUES ("MATH 152", "Calculus and Analytic Geometry II");
INSERT INTO course (course_id, title) VALUES ("MATH 155", "Applied Calculus");
INSERT INTO course (course_id, title) VALUES ("MATH 215", "Applied Finite Mathematics");
INSERT INTO course (course_id, title) VALUES ("MATH 221", "Introduction to Linear Algebra");
INSERT INTO course (course_id, title) VALUES ("MATH 225", "Introduction to Differential Equations");
INSERT INTO course (course_id, title) VALUES ("MATH 251", "Multivariable Calculus");
INSERT INTO course (course_id, title) VALUES ("MATH 301", "Introduction to Mathematical Analysis I");
INSERT INTO course (course_id, title) VALUES ("MATH 302", "Introduction to Mathematical Analysis II");
INSERT INTO course (course_id, title) VALUES ("MATH 341", "Computational Methods");
INSERT INTO course (course_id, title) VALUES ("MATH 355", "Biomathematics");
INSERT INTO course (course_id, title) VALUES ("MATH 365", "Financial Mathematics for Actuaries");
INSERT INTO course (course_id, title) VALUES ("MATH 385", "Introduction to Mathematical Modeling");
INSERT INTO course (course_id, title) VALUES ("MATH 404", "Introduction to Partial Differential Equations I");
INSERT INTO course (course_id, title) VALUES ("MATH 407", "Intro to Modern Algebra & Number Theory");
INSERT INTO course (course_id, title) VALUES ("MATH 411", "Linear Algebra");
INSERT INTO course (course_id, title) VALUES ("MATH 413", "Number Theory");
INSERT INTO course (course_id, title) VALUES ("MATH 430", "Matrix Analysis");
INSERT INTO course (course_id, title) VALUES ("MATH 475", "Combinatorics and Graph Theory");
INSERT INTO course (course_id, title) VALUES ("MATH 481", "Mathematical Modeling");
INSERT INTO course (course_id, title) VALUES ("MATH 486", "Discrete Dynamical Systems");
INSERT INTO course (course_id, title) VALUES ("MCS 101", "Media Literacy");
INSERT INTO course (course_id, title) VALUES ("MCS 222", "Introduction to Media & Communication Studies");
INSERT INTO course (course_id, title) VALUES ("MCS 333", "History and Theory of Mass Communication and Media Studies");
INSERT INTO course (course_id, title) VALUES ("MCS 334", "Media & Globalization");
INSERT INTO course (course_id, title) VALUES ("MCS 355", "Social Media: Networking and Mobility.");
INSERT INTO course (course_id, title) VALUES ("MCS 370", "Special Topics in Media and Communication Studies");
INSERT INTO course (course_id, title) VALUES ("MCS 390", "Transcultural Studies in Global Television");
INSERT INTO course (course_id, title) VALUES ("MCS 395", "Television Production Techniques I");
INSERT INTO course (course_id, title) VALUES ("MCS 404", "Internship");
INSERT INTO course (course_id, title) VALUES ("MCS 484", "Media Production Fellows");
INSERT INTO course (course_id, title) VALUES ("MCS 499", "Capstone Senior Seminar");
INSERT INTO course (course_id, title) VALUES ("MGMT 210", "The Practice of Management");
INSERT INTO course (course_id, title) VALUES ("MGMT 310", "Human Resource Management");
INSERT INTO course (course_id, title) VALUES ("MGMT 360", "Business Law");
INSERT INTO course (course_id, title) VALUES ("MGMT 385", "Business Ethics & Society");
INSERT INTO course (course_id, title) VALUES ("MGMT 410", "Production Management");
INSERT INTO course (course_id, title) VALUES ("MGMT 425", "Marketing");
INSERT INTO course (course_id, title) VALUES ("MGMT 489", "Seminar in Management and Administration");
INSERT INTO course (course_id, title) VALUES ("MLL 190", "The World of Language I");
INSERT INTO course (course_id, title) VALUES ("MLL 191", "The World of Language II");
INSERT INTO course (course_id, title) VALUES ("MLL 210", "Africa: Culture and Development");
INSERT INTO course (course_id, title) VALUES ("MLL 220", "Film and Society in China");
INSERT INTO course (course_id, title) VALUES ("MLL 230", "World Language Communities");
INSERT INTO course (course_id, title) VALUES ("MLL 271", "Introduction to Modern Russian Civilization and Culture");
INSERT INTO course (course_id, title) VALUES ("MLL 280", "Introduction to the Spanish-Speaking World");
INSERT INTO course (course_id, title) VALUES ("MLL 299", "MLLI Experiential Learning");
INSERT INTO course (course_id, title) VALUES ("MLL 300", "Selected Topics in Modern Languages and Linguistics");
INSERT INTO course (course_id, title) VALUES ("MLL 301", "Textual Analysis: Words, Images, Music");
INSERT INTO course (course_id, title) VALUES ("MLL 305", "Introduction to Intercultural Communication");
INSERT INTO course (course_id, title) VALUES ("MLL 315", "Images of Society in Contemporary Korean Films");
INSERT INTO course (course_id, title) VALUES ("MLL 322", "Gender, Race, and Media");
INSERT INTO course (course_id, title) VALUES ("MLL 327", "Modern Japanese Culture");
INSERT INTO course (course_id, title) VALUES ("MLL 406", "Theory and History of Intercultural Media");
INSERT INTO course (course_id, title) VALUES ("MLL 470", "L2 Acquisition and Learning: Theory to Practice");
INSERT INTO course (course_id, title) VALUES ("MLL 480", "Transcultural Studies in Global Television");
INSERT INTO course (course_id, title) VALUES ("MUSC 101", "Fundamentals of Music Theory");
INSERT INTO course (course_id, title) VALUES ("MUSC 111", "Musicianship Laboratory II");
INSERT INTO course (course_id, title) VALUES ("MUSC 112", "Music Repertoire");
INSERT INTO course (course_id, title) VALUES ("MUSC 126", "Theory II: Form and Analysis");
INSERT INTO course (course_id, title) VALUES ("MUSC 162", "Diction: French");
INSERT INTO course (course_id, title) VALUES ("MUSC 170", "Beginning Voice Class");
INSERT INTO course (course_id, title) VALUES ("MUSC 171", "Intermediate Voice Class");
INSERT INTO course (course_id, title) VALUES ("MUSC 175", "Intermediate Vocal Methods");
INSERT INTO course (course_id, title) VALUES ("MUSC 177", "Keyboard Skills II");
INSERT INTO course (course_id, title) VALUES ("MUSC 179", "Keyboard Skills IV");
INSERT INTO course (course_id, title) VALUES ("MUSC 180", "Beginning Piano Class");
INSERT INTO course (course_id, title) VALUES ("MUSC 181", "Intermediate Piano Class");
INSERT INTO course (course_id, title) VALUES ("MUSC 183", "String Methods: Cello and Bass");
INSERT INTO course (course_id, title) VALUES ("MUSC 187", "Intermediate Brass Methods");
INSERT INTO course (course_id, title) VALUES ("MUSC 189", "Guitar Methods");
INSERT INTO course (course_id, title) VALUES ("MUSC 191", "Recital Preparation");
INSERT INTO course (course_id, title) VALUES ("MUSC 211", "Musicianship Laboratory IV");
INSERT INTO course (course_id, title) VALUES ("MUSC 214", "The History of Jazz: Origins-Present");
INSERT INTO course (course_id, title) VALUES ("MUSC 215", "Introduction to Black Music");
INSERT INTO course (course_id, title) VALUES ("MUSC 219", "Introduction to Digital Audio Workstations");
INSERT INTO course (course_id, title) VALUES ("MUSC 222", "Jazz Arranging");
INSERT INTO course (course_id, title) VALUES ("MUSC 226", "Theory IV: Music Writing");
INSERT INTO course (course_id, title) VALUES ("MUSC 230", "Musics of the World");
INSERT INTO course (course_id, title) VALUES ("MUSC 252", "Music in Wartime");
INSERT INTO course (course_id, title) VALUES ("MUSC 303", "UMBC Camerata--Chamber Choir");
INSERT INTO course (course_id, title) VALUES ("MUSC 304", "UMBC Jubilee Singers");
INSERT INTO course (course_id, title) VALUES ("MUSC 305", "UMBC Symphony Orchestra");
INSERT INTO course (course_id, title) VALUES ("MUSC 307", "Small Ensemble");
INSERT INTO course (course_id, title) VALUES ("MUSC 308", "UMBC Wind Ensemble");
INSERT INTO course (course_id, title) VALUES ("MUSC 309", "UMBC New Music Ensemble");
INSERT INTO course (course_id, title) VALUES ("MUSC 310", "Beginning Gamelan");
INSERT INTO course (course_id, title) VALUES ("MUSC 311", "Free Composition");
INSERT INTO course (course_id, title) VALUES ("MUSC 312", "Composition");
INSERT INTO course (course_id, title) VALUES ("MUSC 319", "Advanced Topics in Music Technology");
INSERT INTO course (course_id, title) VALUES ("MUSC 320", "UMBC Jazz Ensemble");
INSERT INTO course (course_id, title) VALUES ("MUSC 322", "Music History II");
INSERT INTO course (course_id, title) VALUES ("MUSC 324", "Small Ensemble Jazz Group");
INSERT INTO course (course_id, title) VALUES ("MUSC 385", "Intermediate Conducting");
INSERT INTO course (course_id, title) VALUES ("MUSC 400", "Special Projects");
INSERT INTO course (course_id, title) VALUES ("MUSC 416", "Analog Recording Perspectives");
INSERT INTO course (course_id, title) VALUES ("MUSC 480", "Topics in Music, Art and Society");
INSERT INTO course (course_id, title) VALUES ("NAVY 101", "Sea Power and Maritime Affairs");
INSERT INTO course (course_id, title) VALUES ("NAVY 105", "Naval Science Leadership Lab");
INSERT INTO course (course_id, title) VALUES ("PHED 103", "Team Handball");
INSERT INTO course (course_id, title) VALUES ("PHED 105", "Basketball");
INSERT INTO course (course_id, title) VALUES ("PHED 109", "Jogging");
INSERT INTO course (course_id, title) VALUES ("PHED 111", "Cardio Fitness");
INSERT INTO course (course_id, title) VALUES ("PHED 112", "Beginning Swimming");
INSERT INTO course (course_id, title) VALUES ("PHED 113", "Intermediate Swimming");
INSERT INTO course (course_id, title) VALUES ("PHED 121", "Physical Fitness");
INSERT INTO course (course_id, title) VALUES ("PHED 123", "Sports Officiating");
INSERT INTO course (course_id, title) VALUES ("PHED 125", "Volleyball");
INSERT INTO course (course_id, title) VALUES ("PHED 133", "Walking and Jogging");
INSERT INTO course (course_id, title) VALUES ("PHED 135", "Softball");
INSERT INTO course (course_id, title) VALUES ("PHED 137", "Tennis");
INSERT INTO course (course_id, title) VALUES ("PHED 143", "Bowling -- Ten Pins");
INSERT INTO course (course_id, title) VALUES ("PHED 144", "Soccer (outdoor)");
INSERT INTO course (course_id, title) VALUES ("PHED 146", "Weight Training/Physical Fitness");
INSERT INTO course (course_id, title) VALUES ("PHED 153", "Scuba");
INSERT INTO course (course_id, title) VALUES ("PHED 157", "Advanced Open Water Scuba");
INSERT INTO course (course_id, title) VALUES ("PHED 160", "Racquetball");
INSERT INTO course (course_id, title) VALUES ("PHED 162", "Pom & Drill");
INSERT INTO course (course_id, title) VALUES ("PHED 164", "Waterpolo");
INSERT INTO course (course_id, title) VALUES ("PHED 193", "Marching and Pep Band");
INSERT INTO course (course_id, title) VALUES ("PHIL 100", "Introduction to Philosophy");
INSERT INTO course (course_id, title) VALUES ("PHIL 146", "Critical Thinking");
INSERT INTO course (course_id, title) VALUES ("PHIL 150", "Contemporary Moral Issues");
INSERT INTO course (course_id, title) VALUES ("PHIL 152", "Introduction to Moral Theory");
INSERT INTO course (course_id, title) VALUES ("PHIL 251", "Ethical Issues in Science and Engineering");
INSERT INTO course (course_id, title) VALUES ("PHIL 322", "History of Philosophy: Modern");
INSERT INTO course (course_id, title) VALUES ("PHIL 346", "Deductive Logic");
INSERT INTO course (course_id, title) VALUES ("PHIL 353", "Morality and Psychology");
INSERT INTO course (course_id, title) VALUES ("PHIL 372", "Philosophy of Science");
INSERT INTO course (course_id, title) VALUES ("PHIL 380", "Philosophy of Mind");
INSERT INTO course (course_id, title) VALUES ("PHIL 399B", "Topics in Philosophy");
INSERT INTO course (course_id, title) VALUES ("PHIL 484", "Kant's Theoretical Philosophy");
INSERT INTO course (course_id, title) VALUES ("PHIL 498", "Advanced Topics in Philosophy");
INSERT INTO course (course_id, title) VALUES ("PHIL 499", "Advanced Topics in Philosophy");
INSERT INTO course (course_id, title) VALUES ("PHYS 105", "Ideas in Astronomy");
INSERT INTO course (course_id, title) VALUES ("PHYS 106", "Introduction to Astrobiology");
INSERT INTO course (course_id, title) VALUES ("PHYS 111", "Basic Physics I");
INSERT INTO course (course_id, title) VALUES ("PHYS 112", "Basic Physics II");
INSERT INTO course (course_id, title) VALUES ("PHYS 121", "Introductory Physics I");
INSERT INTO course (course_id, title) VALUES ("PHYS 121H", "Introductory Physics I - Honors");
INSERT INTO course (course_id, title) VALUES ("PHYS 122", "Introductory Physics II");
INSERT INTO course (course_id, title) VALUES ("PHYS 122H", "Introductory Physics II");
INSERT INTO course (course_id, title) VALUES ("PHYS 122L", "Introductory Physics Laboratory");
INSERT INTO course (course_id, title) VALUES ("PHYS 220", "Introduction to Computational Physics");
INSERT INTO course (course_id, title) VALUES ("PHYS 224", "Vibrations and Waves");
INSERT INTO course (course_id, title) VALUES ("PHYS 304", "Fundamentals of Astronomy and Astrophysics");
INSERT INTO course (course_id, title) VALUES ("PHYS 320L", "Electronics for Scientists");
INSERT INTO course (course_id, title) VALUES ("PHYS 321", "Intermediate Mechanics");
INSERT INTO course (course_id, title) VALUES ("PHYS 324", "Modern Physics");
INSERT INTO course (course_id, title) VALUES ("PHYS 408", "Optics");
INSERT INTO course (course_id, title) VALUES ("PHYS 416", "Extragalactic Astronomy and Cosmology");
INSERT INTO course (course_id, title) VALUES ("PHYS 424", "Introduction to Quantum Mechanics");
INSERT INTO course (course_id, title) VALUES ("PHYS 431L", "Modern Physics Laboratory");
INSERT INTO course (course_id, title) VALUES ("POLI 100", "American Government and Politics");
INSERT INTO course (course_id, title) VALUES ("POLI 209", "Selected Topics in Political Science");
INSERT INTO course (course_id, title) VALUES ("POLI 230", "Introduction to Constitutional Law (SS)");
INSERT INTO course (course_id, title) VALUES ("POLI 281", "International Relations (w/ writing focus)");
INSERT INTO course (course_id, title) VALUES ("POLI 301", "Research Methods in Political Science");
INSERT INTO course (course_id, title) VALUES ("POLI 309", "Selected Topics in Political Science");
INSERT INTO course (course_id, title) VALUES ("POLI 319", "Selected Topics in Political Philosophy");
INSERT INTO course (course_id, title) VALUES ("POLI 320", "American Political Thought");
INSERT INTO course (course_id, title) VALUES ("POLI 323", "The Presidency");
INSERT INTO course (course_id, title) VALUES ("POLI 327", "Interest Groups and Lobbyists");
INSERT INTO course (course_id, title) VALUES ("POLI 337", "Comparative Justice");
INSERT INTO course (course_id, title) VALUES ("POLI 338", "Women, Gender, and Law");
INSERT INTO course (course_id, title) VALUES ("POLI 350", "The Policy-Making Process");
INSERT INTO course (course_id, title) VALUES ("POLI 352", "Administrative Law");
INSERT INTO course (course_id, title) VALUES ("POLI 353", "Governmental Budgeting and Financial Administration");
INSERT INTO course (course_id, title) VALUES ("POLI 360", "Comparative Political Analysis");
INSERT INTO course (course_id, title) VALUES ("POLI 361", "Comparative Political Analysis");
INSERT INTO course (course_id, title) VALUES ("POLI 377", "Latin American Politics");
INSERT INTO course (course_id, title) VALUES ("POLI 379", "War and Film");
INSERT INTO course (course_id, title) VALUES ("POLI 380", "International Relations Theory");
INSERT INTO course (course_id, title) VALUES ("POLI 384L", "Model United Nations");
INSERT INTO course (course_id, title) VALUES ("POLI 390", "American Foreign Policy");
INSERT INTO course (course_id, title) VALUES ("POLI 409", "Selected Topics in Political Science");
INSERT INTO course (course_id, title) VALUES ("POLI 429", "Selected Topics in American Government and Politics");
INSERT INTO course (course_id, title) VALUES ("POLI 432", "Civil Rights");
INSERT INTO course (course_id, title) VALUES ("POLI 438", "Legal Internship");
INSERT INTO course (course_id, title) VALUES ("POLI 439", "Selected Topics in Public Law");
INSERT INTO course (course_id, title) VALUES ("POLI 445", "Law, Politics and American Educational Policy");
INSERT INTO course (course_id, title) VALUES ("POLI 448", "Internship in Policy, Politics, and Administration");
INSERT INTO course (course_id, title) VALUES ("POLI 450", "Public Management & Public Policy: Pursuing Excellence in Public Service");
INSERT INTO course (course_id, title) VALUES ("POLI 469", "Selected Topics in Comparative Politics");
INSERT INTO course (course_id, title) VALUES ("POLI 470", "Politics of Human Rights");
INSERT INTO course (course_id, title) VALUES ("POLI 474", "Democratization");
INSERT INTO course (course_id, title) VALUES ("POLI 485", "Dynamics of the Arab-Israeli Conflict");
INSERT INTO course (course_id, title) VALUES ("POLI 486", "Middle East International Relations.");
INSERT INTO course (course_id, title) VALUES ("POLI 488", "Politics and International Relations of South Asia");
INSERT INTO course (course_id, title) VALUES ("POLI 489", "Selected Topics in International Relations");
INSERT INTO course (course_id, title) VALUES ("PSYC 100", "Introduction to Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 100H", "Introduction to Psychology - Honors");
INSERT INTO course (course_id, title) VALUES ("PSYC 200", "Child Developmental Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 210", "Psychology of Learning");
INSERT INTO course (course_id, title) VALUES ("PSYC 211", "The Science and Profession of Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 216", "Foundations of Leadership Development");
INSERT INTO course (course_id, title) VALUES ("PSYC 230", "Psychology and Culture");
INSERT INTO course (course_id, title) VALUES ("PSYC 285", "Abnormal Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 304", "Adolescent Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 305", "The Exceptional Child");
INSERT INTO course (course_id, title) VALUES ("PSYC 306", "Lifespan Human Development");
INSERT INTO course (course_id, title) VALUES ("PSYC 307", "Psychology of Aging");
INSERT INTO course (course_id, title) VALUES ("PSYC 308", "Child Maltreatment");
INSERT INTO course (course_id, title) VALUES ("PSYC 309", "Psychology: Exploring the Discipline and Careers");
INSERT INTO course (course_id, title) VALUES ("PSYC 311", "Research Methods in Psychology I");
INSERT INTO course (course_id, title) VALUES ("PSYC 312", "Research Methods in Psychology II");
INSERT INTO course (course_id, title) VALUES ("PSYC 316", "Language and Thought");
INSERT INTO course (course_id, title) VALUES ("PSYC 320", "Psychological Assessment");
INSERT INTO course (course_id, title) VALUES ("PSYC 324", "Introduction to Interviewing Techniques");
INSERT INTO course (course_id, title) VALUES ("PSYC 330", "Child Development and Culture");
INSERT INTO course (course_id, title) VALUES ("PSYC 335", "Physiological Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 340", "Social Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 342", "The Psychology of Aggression and Antisocial Behavior");
INSERT INTO course (course_id, title) VALUES ("PSYC 345", "Introduction to Clinical Psychology and Psychotherapy");
INSERT INTO course (course_id, title) VALUES ("PSYC 346", "Industrial/Organizational Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 353", "Morality and Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 357", "Psychology of Women");
INSERT INTO course (course_id, title) VALUES ("PSYC 360", "Psychology of Motivation");
INSERT INTO course (course_id, title) VALUES ("PSYC 365", "Children with Disabilities");
INSERT INTO course (course_id, title) VALUES ("PSYC 370", "Sensation and Perception");
INSERT INTO course (course_id, title) VALUES ("PSYC 375", "Neuroanatomy");
INSERT INTO course (course_id, title) VALUES ("PSYC 380", "Personality");
INSERT INTO course (course_id, title) VALUES ("PSYC 382", "Child and Adolescent Psychopathology");
INSERT INTO course (course_id, title) VALUES ("PSYC 385", "Health Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 387", "Community Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 400", "Seminar in Developmental Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 406", "Advanced Behavior Pathology");
INSERT INTO course (course_id, title) VALUES ("PSYC 411", "Applied Behavior Analysis");
INSERT INTO course (course_id, title) VALUES ("PSYC 415", "Seminar in Cognitive Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 421", "Parenting");
INSERT INTO course (course_id, title) VALUES ("PSYC 444", "Psychology of Sexual Orientation & Gender Identity");
INSERT INTO course (course_id, title) VALUES ("PSYC 455", "Schizophrenia");
INSERT INTO course (course_id, title) VALUES ("PSYC 465", "Family Psychology");
INSERT INTO course (course_id, title) VALUES ("PSYC 493", "Advanced Topics in Psychology");
INSERT INTO course (course_id, title) VALUES ("PUB 150H", "Public Affairs Scholars Seminar");
INSERT INTO course (course_id, title) VALUES ("RLST 202", "Judaism in the Time of Jesus and Hillel");
INSERT INTO course (course_id, title) VALUES ("RLST 314", "Islam in Africa");
INSERT INTO course (course_id, title) VALUES ("RLST 463", "Jews, Christians and Muslims in the Middle Ages");
INSERT INTO course (course_id, title) VALUES ("RUSS 102", "Basic Russian II");
INSERT INTO course (course_id, title) VALUES ("RUSS 202", "Continuing Russian I");
INSERT INTO course (course_id, title) VALUES ("RUSS 300", "Special Projects in Russian Language");
INSERT INTO course (course_id, title) VALUES ("RUSS 302", "Continuing Russian III");
INSERT INTO course (course_id, title) VALUES ("RUSS 304", "Intermediate Russian Conversation II");
INSERT INTO course (course_id, title) VALUES ("RUSS 321", "The Russians' World - I");
INSERT INTO course (course_id, title) VALUES ("RUSS 415", "Political Russian");
INSERT INTO course (course_id, title) VALUES ("SCI 100", "Water; An Interdisciplinary Study (MS)");
INSERT INTO course (course_id, title) VALUES ("SCI 101L", "Quantitative Reasoning: Measurement and Skills Lab");
INSERT INTO course (course_id, title) VALUES ("SOCY 101", "Basic Concepts in Sociology");
INSERT INTO course (course_id, title) VALUES ("SOCY 101Y", "Basic Concepts in Sociology");
INSERT INTO course (course_id, title) VALUES ("SOCY 201", "Social Problems in American Society");
INSERT INTO course (course_id, title) VALUES ("SOCY 204", "Diversity and Pluralism: An Interdisciplinary Perspective");
INSERT INTO course (course_id, title) VALUES ("SOCY 300", "Methodology of Social Research");
INSERT INTO course (course_id, title) VALUES ("SOCY 301", "Analysis of Sociological Data");
INSERT INTO course (course_id, title) VALUES ("SOCY 310", "Social Stratification and Inequality");
INSERT INTO course (course_id, title) VALUES ("SOCY 321", "Race and Ethnic Relations");
INSERT INTO course (course_id, title) VALUES ("SOCY 333", "Human Sexuality in Cross-Cultural Perspective");
INSERT INTO course (course_id, title) VALUES ("SOCY 351", "Medical Sociology");
INSERT INTO course (course_id, title) VALUES ("SOCY 352", "Issues in Health Care");
INSERT INTO course (course_id, title) VALUES ("SOCY 353", "Marriage and the Family");
INSERT INTO course (course_id, title) VALUES ("SOCY 354", "Social Bases of Public and Community Health");
INSERT INTO course (course_id, title) VALUES ("SOCY 359", "Death and Dying");
INSERT INTO course (course_id, title) VALUES ("SOCY 372", "Juvenile Delinquency");
INSERT INTO course (course_id, title) VALUES ("SOCY 374", "Drugs and Alcohol in Society");
INSERT INTO course (course_id, title) VALUES ("SOCY 396", "Community Service and Learning Internship");
INSERT INTO course (course_id, title) VALUES ("SOCY 409", "Sociological Theory");
INSERT INTO course (course_id, title) VALUES ("SOCY 415", "Higher Education and Social Inequality");
INSERT INTO course (course_id, title) VALUES ("SOCY 418", "SAS for Social Scientists");
INSERT INTO course (course_id, title) VALUES ("SOCY 433", "Gender, Work, and Family in Cross-Cultural Perspective");
INSERT INTO course (course_id, title) VALUES ("SOCY 452", "Health Care Organization and Delivery");
INSERT INTO course (course_id, title) VALUES ("SOCY 458", "Sociology of Mental Health and Illness");
INSERT INTO course (course_id, title) VALUES ("SOWK 240", "Information Technology in Social Work");
INSERT INTO course (course_id, title) VALUES ("SOWK 260", "Social Welfare, Social Policy, and Social Work I");
INSERT INTO course (course_id, title) VALUES ("SOWK 360", "Social Welfare, Social Policy, and Social Work II");
INSERT INTO course (course_id, title) VALUES ("SOWK 370", "Social Work and the Criminal Justice System");
INSERT INTO course (course_id, title) VALUES ("SOWK 372", "Social Work and Health Care");
INSERT INTO course (course_id, title) VALUES ("SOWK 374", "Social Work with Immigrants and Refugees");
INSERT INTO course (course_id, title) VALUES ("SOWK 387", "Policies, Programs, and Services for Children");
INSERT INTO course (course_id, title) VALUES ("SOWK 388", "Human Behavior and the Social Environment");
INSERT INTO course (course_id, title) VALUES ("SOWK 389", "Human Behavior II");
INSERT INTO course (course_id, title) VALUES ("SOWK 397", "Social Work Methods I: Introduction to Practice");
INSERT INTO course (course_id, title) VALUES ("SOWK 470", "Social Work Research");
INSERT INTO course (course_id, title) VALUES ("SOWK 482", "Field Instruction II");
INSERT INTO course (course_id, title) VALUES ("SOWK 483", "Social Work Methods III: Selected Intervention Strategies, Research, and Evaluation");
INSERT INTO course (course_id, title) VALUES ("SPAN 101", "Elementary Spanish I");
INSERT INTO course (course_id, title) VALUES ("SPAN 102", "Elementary Spanish II");
INSERT INTO course (course_id, title) VALUES ("SPAN 103", "Intensive Review of Elementary Spanish");
INSERT INTO course (course_id, title) VALUES ("SPAN 201", "Intermediate Spanish I");
INSERT INTO course (course_id, title) VALUES ("SPAN 202", "Intermediate Spanish II");
INSERT INTO course (course_id, title) VALUES ("SPAN 301", "Advanced Spanish I");
INSERT INTO course (course_id, title) VALUES ("SPAN 302", "Advanced Spanish II");
INSERT INTO course (course_id, title) VALUES ("SPAN 304", "Spanish for Heritage Spanish Speakers I");
INSERT INTO course (course_id, title) VALUES ("SPAN 307", "España y sus Culturas I");
INSERT INTO course (course_id, title) VALUES ("SPAN 308", "Latinoamérica y sus Culturas I");
INSERT INTO course (course_id, title) VALUES ("SPAN 311", "España y sus culturas II");
INSERT INTO course (course_id, title) VALUES ("SPAN 401", "Studies in Spanish Language");
INSERT INTO course (course_id, title) VALUES ("SPAN 421", "Studies in Hispanic Literature");
INSERT INTO course (course_id, title) VALUES ("SPAN 472", "Topics in Latin American Society");
INSERT INTO course (course_id, title) VALUES ("SPCH 100", "Public Communication");
INSERT INTO course (course_id, title) VALUES ("SPCH 210", "Interpersonal Communication");
INSERT INTO course (course_id, title) VALUES ("STAT 121", "Introduction to Statistics for the Social Sciences");
INSERT INTO course (course_id, title) VALUES ("STAT 350", "Statistics with Applications in the Biological Sciences");
INSERT INTO course (course_id, title) VALUES ("STAT 351", "Applied Statistics for Business and Economics");
INSERT INTO course (course_id, title) VALUES ("STAT 355", "Introduction to Probability and Statistics for Scientists and Engineers");
INSERT INTO course (course_id, title) VALUES ("STAT 365", "Financial Mathematics for Actuaries");
INSERT INTO course (course_id, title) VALUES ("STAT 405", "Survey Sampling");
INSERT INTO course (course_id, title) VALUES ("STAT 414", "Environmental Statistics");
INSERT INTO course (course_id, title) VALUES ("STAT 453", "Introduction to Mathematical Statistics");
INSERT INTO course (course_id, title) VALUES ("STAT 470", "Probability for Actuarial Science");
INSERT INTO course (course_id, title) VALUES ("THTR 100", "Introduction to Theatre Scenography");
INSERT INTO course (course_id, title) VALUES ("THTR 104", "Introduction to Costume");
INSERT INTO course (course_id, title) VALUES ("THTR 110", "Introduction to Acting");
INSERT INTO course (course_id, title) VALUES ("THTR 202", "Introduction to Dramatic Literature");
INSERT INTO course (course_id, title) VALUES ("THTR 221", "Craft of Acting II");
INSERT INTO course (course_id, title) VALUES ("THTR 222", "Vocal Training for the Actor I");
INSERT INTO course (course_id, title) VALUES ("THTR 231", "Drafting for the Theatre");
INSERT INTO course (course_id, title) VALUES ("THTR 233", "Costume Design");
INSERT INTO course (course_id, title) VALUES ("THTR 234", "Make-up for the Stage");
INSERT INTO course (course_id, title) VALUES ("THTR 237", "Sound Design");
INSERT INTO course (course_id, title) VALUES ("THTR 239", "Movement II: Alexander Technique");
INSERT INTO course (course_id, title) VALUES ("THTR 244", "Script Analysis");
INSERT INTO course (course_id, title) VALUES ("THTR 263", "Theatre Production: Costumes");
INSERT INTO course (course_id, title) VALUES ("THTR 264", "Theatre Production: Scenery");
INSERT INTO course (course_id, title) VALUES ("THTR 325", "Vocal Training for the Actor III");
INSERT INTO course (course_id, title) VALUES ("THTR 335", "Advanced Lighting Design");
INSERT INTO course (course_id, title) VALUES ("THTR 347", "Character and Scene Study I");
INSERT INTO course (course_id, title) VALUES ("THTR 371", "Playwriting");
INSERT INTO course (course_id, title) VALUES ("THTR 390", "Theatre in Production");
INSERT INTO course (course_id, title) VALUES ("THTR 411", "Modern Theatre: History and Practice");
INSERT INTO course (course_id, title) VALUES ("THTR 432", "Design Seminar");
INSERT INTO course (course_id, title) VALUES ("THTR 434", "Patterning and Draping");
INSERT INTO course (course_id, title) VALUES ("THTR 470", "Drama Seminar");
INSERT INTO course (course_id, title) VALUES ("TRS 201", "Transfer Student Seminar");
INSERT INTO course (course_id, title) VALUES ("VPA 225", "Ideas in the Arts");
INSERT INTO course (course_id, title) VALUES ("WOL 102", "Elementary Wolof II");